### PR TITLE
v0.54 updated OTP handling

### LINKED ISSUE #22: Support for new authorization mechanism
Recently new authorization mechanism has been introduced to NK Pro. Briefly it consist of:
- removing CMD_AUTHORIZE completely
- adding temporary password directly to command packets which needs to be authorized
 
Links:
- https://github.com/Nitrokey/nitrokey-pro-firmware/pull/25
- https://github.com/Nitrokey/nitrokey-pro-firmware/pull/29 (updated WRITE_TO_SLOT command)

### LINKED ISSUE #23: Support bigger OTP secrets (up to 40 bytes)
In NK Pro OTP secrets have been extended to support AWS.

Links:
- https://github.com/Nitrokey/nitrokey-pro-firmware/pull/29

### LINKED ISSUE #26: Not updating HOTP counter while editing OTP slot
Storage v0.45
test: test_edit_OTP_slot, test_pro.py in libnitrokey test suite
Ubuntu 16.10

Device is not updating HOTP counter while editing HOTP slot. To test TOTP variant too.
More details in issue linked below.

### LINKED ISSUE #64: Use memset_s
The code contains several occurrence of memset. memset could be optimized away by the compiler which is why memset_s should be used instead, for cases where a key or password or other confidential data has to be overwritten im RAM.

### LINKED ISSUE #70: Clear OTP authorization session on Lock command execution
After locking the device, it should deny subsequent requests for the OTP code.
Precondition: OTP code access is protected by User PIN.

Firmware: v0.52 (latest)
Application: Nitrokey App 1.3.2

Details: https://github.com/Nitrokey/nitrokey-app/issues/385

### PR DESCRIPTION
**Pull request by NKelias**
This reworks the OTP handling to resemble that of the Nitrokey Pro.

### Functional changes:
- OTP secret extended to 40 Bytes
- Authorization changed from pre-authenticated CRC to temporary password in HID report
- OTP counter transferred as 64bit unsigned Integer instead of C-String
- OTP counter is retained when editing slots
- Temporary passwords cleared through `lock_device` operation
- HOTP verification functionality added

### Further changes:
- OTP handlng now uses struct format for message parsing and passing data around
- Replace optimizable `memset` with non-optimizable `memset_safe` function for critical data

closes #70  
closes #64 
closes #26 
closes #22 
closes #23 

Firmware:
[nkstorage_v054_pr85.zip](https://github.com/Nitrokey/nitrokey-storage-firmware/files/2800525/nkstorage_v054_pr85.zip)

### CODE REVIEW

**Comment by jans23** [comment]
While this PR changes the stored OTP data structure, I suggest to include the OTP verification feature (Purism) too, to avoid another subsequent change.

**Comment by szszszsz** [comment]
Related to https://github.com/Nitrokey/nitrokey-storage-firmware/pull/85#issuecomment-458290267  : https://github.com/Nitrokey/nitrokey-storage-firmware/issues/71

**Comment by NKelias** [comment]
Is this the functionality we are talking about:
https://github.com/Nitrokey/nitrokey-pro-firmware/blob/664c11b3e6429551f1b21534efd8ae364047fa87/src/keyboard/report_protocol.c#L445

**Comment by szszszsz** [comment]
Exactly. In short device should be able to calculate HOTP code on a separate slot (not available to read by the usual OTP API), and compare with the received code. If matches, should wink green, or red otherwise. Device should offer 10 attempts (AFAIR). 

Tests, and the client app, are provided here: [nitrokey-hotp-verification].

[nitrokey-hotp-verification]: https://github.com/Nitrokey/nitrokey-hotp-verification

**Comment by NKelias** [comment]
Updated firmware:
[nkstorage_v054_pr85.zip](https://github.com/Nitrokey/nitrokey-storage-firmware/files/2842378/nkstorage_v054_pr85.zip)

**Comment by tlaurion** [comment]
Wasn't merged?

**Pull request merged**
