### PR TITLE
Modified #include filenames to allow building on Linux

### PR DESCRIPTION
**Pull request by adebeun**

### CODE REVIEW

**Comment by szszszsz** [comment]
Hi! Thank you for the patch!
After a brief check it looks like the only changes were:
- correcting file names (case sensitive)
- swapping backslash `\` to slash `/` in path

@adebeun Since you are just after compilation, could you briefly describe the process?

@rudbo Could you check by some occasion is it compiling on Windows on your side?

**Comment by adebeun** [comment]
Correct, the only changes are dealing with Linux slashes and case sensitivity in #include path names.
The compile procedure is as follows:
1) Download and install AVR32 Studio. I used avr32studio-ide-2.6.0.753-linux.gtk.x86_64.zip.
2) Clone the project.
3) Import project into AVR32 Studio: File | Import... | General | Existing Projects into Workspace
4) Rename pm_240.h to pm_231.h. Make a backup of as4e-ide/plugins/com.atmel.avr.toolchains.linux.x86_64_3.0.0.201009140852/os/linux/x86_64/avr32/include/pm_231.h. Replace that pm_231.h with the renamed pm_240.h. (I'm not sure what is the correct way to deal with the pm_240.h header file. Copying pm_240.h to that directory was not enough. I was unable to find a way to persuade AVR32 Studio to use pm_240.h instead of pm_231.h. What do you do with pm_240.h?)
5) Project | Build All. (Works for both Debug and Release versions.)

**Comment by szszszsz** [comment]
Great! Thank you very much!
I will add these instructions to README if you do not mind. Would you like to be mentioned in THANKS file by real name?

**Comment by adebeun** [comment]
Sure, use those instructions as you like. You may use my real name.

**Comment by mupuf** [comment]
Thanks Arthur, I can also confirm that this patch is enough to compile on Archlinux with the instructions you provided.

**Comment by mupuf** [comment]
Oh, and if you are going to change the instructions, please add this:

avr-objcopy -R .eeprom -O ihex USB_MASS.elf firmware.hex

Then follow the instructions as found here to actually flash the device: https://www.nitrokey.com/en/doc/firmware-update-storage

**Comment by szszszsz** [comment]
Just confirmed it works on Ubuntu 17.04 with mentioned replacing `231` with `240`.
@rudbo Is it compiling on your side on Windows?

**Comment by szszszsz** [comment]
I have just received message that it is compiling on Windows. Merged.

**Pull request closed without merging**
