### PR TITLE
Change HID to Interface to generic

### PR DESCRIPTION
**Pull request by NKelias**
This changes the HID interface of the NK Storage device from a keyboard device to a generic HID device to allow 3rd party application access to the interface on Windows 10 versions above 1803.

Resolves https://github.com/Nitrokey/nitrokey-app/issues/392

Compiled Firmware for Testing: [usb_generic_if.zip](https://github.com/Nitrokey/nitrokey-storage-firmware/files/2605671/usb_generic_if.zip)

### CODE REVIEW

**Comment by jans23** [comment]
Is VERSION_MINOR still 52?

**Comment by szszszsz** [comment]
OK! Will be merged after testing the firmware.

**Comment by szszszsz** [comment]
### Content
- [x] Increased firmware version (to 0.53)
- [x] Increased bcdDevice
- [x] Changed HID descriptor

### Tests

#### libnitrokey
Ubuntu 18.04:
- [ ] libnitrokey Python tests (`v3.4.1-21-gef171df`, current `master`),

#### Nitrokey App
- [ ] Test on Ubuntu 18.04,
- [ ] Test on Fedora 29,
- [ ] Test on Windows 10 1809,
- [ ] Test on Windows 10 1803,
- [ ] Test on macOSX 10.13.6.

### Git corrections
- [ ] Squash commits

**Comment by szszszsz** [comment]
HID descriptor from firmware:
```
0x06, 0x00, 0xFF,   /*  Usage Page (FF00h),         */ 
0x09, 0x01,         /*  Usage (01h),                */ 
0xA1, 0x01,         /*  Collection (Application),   */ 
0x09, 0x01,         /*      Usage (01h),            */ 
0x15, 0x00,         /*      Logical Minimum (0),    */ 
0x26, 0xFF, 0x00,   /*      Logical Maximum (255),  */ 
0x75, 0x08,         /*      Report Size (8),        */ 
0x95, 0x40,         /*      Report Count (64),      */ 
0x81, 0x02,         /*      Input (Variable),       */ 
0x09, 0x02,         /*      Usage (02h),            */ 
0x15, 0x00,         /*      Logical Minimum (0),    */ 
0x26, 0xFF, 0x00,   /*      Logical Maximum (255),  */ 
0x75, 0x08,         /*      Report Size (8),        */ 
0x95, 0x40,         /*      Report Count (64),      */ 
0x91, 0x02,         /*      Output (Variable),      */ 
0x09, 0x02,         /*      Usage (02h),            */ 
0x75, 0x08,         /*      Report Size (8),        */ 
0x95, 0x40,         /*      Report Count (64),      */ 
0xB1, 0x02,         /*      Feature (Variable),     */ 
0xC0                /*  End Collection              */ 

```

**Comment by szszszsz** [comment]
@jans23 While we are changing the `bcdDevice` number anyway, perhaps we could start giving it the value equal to the actual firmware version?

**Comment by jans23** [comment]
AFAIK that would be uncommon, at least I haven't seen another device
doing it like that. I understand bcdDevice as a version which is solely
used to indicate if the USB interface has changed or not. I think
Windows uses USB VID, USB PID and bcdDevice as an indicator to install a
new USB driver, which we don't want for every firmware update.

**Comment by szszszsz** [comment]
Hi!
We have published today a new tool for users of Windows 10 1809 (and newer), and Storage v0.52 (and older). It is a bootable image, which allows to unlock the Storage device update feature. The guide for using it is located here: [Using the bootable image]. This should be a one-time operation, to allow to flash firmware v0.53, using which device can communicate under Windows 10 1809. Further updates will be possible to run with the Nitrokey Update Tool, as in the [main firmware update guide].

[Using the bootable image]: https://github.com/Nitrokey/nitrokey-storage-update-boot/blob/master/boot-image-usage-guide.md
[main firmware update guide]: https://www.nitrokey.com/en/documentation/firmware-update-storage

**Pull request closed without merging**
